### ISSUE TITLE
msgbo.php 內的檢視文章不應該是 form

### ISSUE THREAD

**Issue by linroex** [TTPLP/messageboard#10]
對 html 理解錯誤，按鈕就是按鈕，不應該是 form，應該是超連結

**Comment by linroex** [comment]
seemsg.php 亦然

**Comment by xu65k6djo6** [comment]
![button](https://cloud.githubusercontent.com/assets/15827219/11652058/532976e4-9dd0-11e5-917c-a0d643185d47.png)
這樣嗎?

**Comment by linroex** [comment]
已哭
其實你可以用超連結

``` html
<a href="">
```

**Comment by linroex** [comment]
不需要用 js 的地方儘量不要用，因為你難保會不會有電腦沒有 js XDDD
