### ISSUE TITLE
msgbi.php bad...

### ISSUE THREAD

**Issue by linroex** [TTPLP/messageboard#11]
1. 為什麼要存到 Array 中？ 你做了一件多此一舉的事情
2. 為什麼要用 foreach ？同樣沒有意義
3. 試著思考，如何在寫程式達成功能的同時，讓程式碼是適合被閱讀的

**Comment by xu65k6djo6** [comment]
是說
$data[0]=$_POST['name'];
$data[1]=$_POST['email'];
$data[2]=$_POST['title'];
$data[3]=$_POST['comments'];
fputcsv($fp, $data);
這些嗎?
我才能
![csvexample](https://cloud.githubusercontent.com/assets/15827219/11651824/a52682c2-9dce-11e5-9fbf-0ee33c0b2869.png)
這樣存在csv裡
還是有別的寫法

**Comment by linroex** [comment]
是的，這樣更好閱讀

—林熙哲。聽風 

http://me.coder.tw

**Comment by linroex** [comment]
能不能寫成

``` php
fputcsv($fp, [$_POST['name'], $_POST['name'], $_POST['name'], $_POST['name']]);
```

或是比較好看的寫法

``` php
fputcsv($fp, [
    $_POST['name'], 
    $_POST['name'], 
    $_POST['name'], 
    $_POST['name']
]);
```

不建議用 data[0] 的原因，是因為程式碼不好閱讀

我寧願你寫成

``` php
$name = $_POST['name'];
```
