### ISSUE TITLE
試著用 table 排版 seemsg 對文章的顯示

### ISSUE THREAD

**Issue by linroex** [TTPLP/messageboard#12]

**Comment by xu65k6djo6** [comment]
![tablequest](https://cloud.githubusercontent.com/assets/15827219/11651881/49ed80b2-9dcf-11e5-88b9-4d4dbf3599f7.png)
14~17行要怎麼縮排

**Comment by linroex** [comment]
有問題直接用slack

—林熙哲。聽風 

http://me.coder.tw
