### ISSUE TITLE
使用流程設計建議

### ISSUE THREAD

**Issue by linroex** [TTPLP/messageboard#2]
- seemsg 應該要有 add 按鈕
- 返回後，不應該有原本的資料

**Comment by xu65k6djo6** [comment]
add按鈕是新增文章嗎?

**Comment by linroex** [comment]
yes

—林熙哲。聽風 

http://me.coder.tw

**Comment by xu65k6djo6** [comment]
所以我要在檢視文章那個頁面設置一個add按鈕然後按下他之後會跑到
![index](https://cloud.githubusercontent.com/assets/15827219/11650952/28cb71ac-9dc8-11e5-92b7-4b3f42c303bd.png)
這個頁面嗎?

**Comment by linroex** [comment]
下次用slack問，是這樣沒錯

—林熙哲。聽風 

http://me.coder.tw
