### ISSUE TITLE
這刪除功能也太不直覺=__=

### ISSUE THREAD

**Issue by linroex** [TTPLP/messageboard#23]
所以我是要刪除哪篇...

![2015-12-15 4 12 05](https://cloud.githubusercontent.com/assets/1254953/11805446/9ba6bd52-a346-11e5-9bb2-a4db0f8b56bf.jpg)

**Comment by xu65k6djo6** [comment]
因為我設定不是你發的文不能勾選刪除

**Comment by linroex** [comment]
瞭解

—林熙哲。聽風 

http://me.coder.tw
