### ISSUE TITLE
檢查所有的錯誤提示

### ISSUE THREAD

**Issue by linroex** [TTPLP/messageboard#3]
Warning、Notice 都算是，把他們處理掉

**Comment by xu65k6djo6** [comment]
sublime要怎麼看warning

**Comment by linroex** [comment]
sublime看不到，他只是文字編輯，php執行後就看得到了

—林熙哲。聽風 

http://me.coder.tw

**Comment by linroex** [comment]
後來的處理方式？

**Comment by xu65k6djo6** [comment]
我把$count$number這些需要++的設一個初始值0
