### ISSUE TITLE
單獨檢視留言頁面？

### ISSUE THREAD

**Issue by linroex** [TTPLP/messageboard#5]
seemsg 頁面會列出所有留言
但我希望 seemsg 只會列出標題，超連結點入標題後，才會顯示詳細資訊

**Comment by xu65k6djo6** [comment]
所以我按下不同的標題都會跑到不同的網址上嗎

**Comment by linroex** [comment]
是的

—林熙哲。聽風 

http://me.coder.tw

**Comment by xu65k6djo6** [comment]
![tablequest](https://cloud.githubusercontent.com/assets/15827219/11651954/a0284ef8-9dcf-11e5-9501-f3ea484b327e.png)
第16行的寫法對嗎

**Comment by linroex** [comment]
great
